function Budget(props) {

  return (
    <div>
      <div>
        <div className="">
          Home
      </div>
        <div>
          expenses
      </div>
        <div>
          Target
      </div>
      </div>
      <div>
        <div>
          Food
      </div>
        <div>
          expenses
      </div>
        <div>
          Target
      </div>
      </div>
      <div>
        <div>
          Shopping
      </div>
        <div>
          expenses
      </div>
        <div>
          Target
      </div>
      </div>
      <div>
        <div>
          Utilities
      </div>
        <div>
          expenses
      </div>
        <div>
          Target
      </div>
      </div>
      <div>
        <div>
          Household
      </div>
        <div>
          expenses
      </div>
        <div>
          Target
      </div>
      </div>
      <div>
        <div>
          Transportation
      </div>
        <div>
          expenses
      </div>
        <div>
          Target
      </div>
      </div>
    </div>
  );
}

export default Budget;